### ISSUE TITLE
Add text to specify user action in CCG Member Position Selection in CCT Web

### ISSUE THREAD

**Issue by ccg-lem** [dfo-mpo/ccg-cct#100]
Add text to help guide user to Compare/Similar Search step in CCG Member pathway.

ENG: Click Next to compare or find similar positions within the organization to your selected position below.
FR: Cliquez sur Suivant pour comparer ou trouver des postes similaires au sein de l'organisation à votre poste sélectionné ci-dessous.

![image](https://user-images.githubusercontent.com/82117975/123316469-de372300-d4fa-11eb-9e69-2d8b2496136a.png)

**Comment by trudge-64** [comment]
Dan added the text and this was merged into master
