### ISSUE TITLE
Certificate Descriptions table in database missing ACTIVE column in Database

### ISSUE THREAD

**Issue by ccg-lem** [dfo-mpo/ccg-cct#111]
Need to be able to Inactivate the description via the Admin tool. Please add the ACTIVE column to the CertificateDescriptions table. 

![image](https://user-images.githubusercontent.com/82117975/123668638-4c385e80-d809-11eb-91b1-3b6ef226061f.png)

**Comment by raminderus** [comment]
Added a new column in the table and created a pull request

**Comment by alfredboum** [comment]
Issue fixed and pull request created from branch CertificateDescriptions
