### ISSUE TITLE
Move PREVIOUS and NEXT Buttons to top of page

### ISSUE THREAD

**Issue by ccg-lem** [dfo-mpo/ccg-cct#120]
To facilitate user navigation, move PREVIOUS and NEXT buttons to top of page views

![image](https://user-images.githubusercontent.com/82117975/124497554-ff183780-dd88-11eb-9047-f5d1ef1f51d8.png)

**Comment by trudge-64** [comment]
This has been fixed and merged into master

**Comment by ccg-lem** [comment]
There are some pages that haven't been updated yet:

![image](https://user-images.githubusercontent.com/82117975/125951269-cd32c2e1-4c62-43e8-8273-7f6a53204f84.png)

![image](https://user-images.githubusercontent.com/82117975/125951344-a48a6221-1cff-4337-9c96-5484e344c600.png)

**Comment by trudge-64** [comment]
Ahhh, I missed those pages. Will do.
