### ISSUE TITLE
Fix SearchSimilarJob table in Database

### ISSUE THREAD

**Issue by ccg-lem** [dfo-mpo/ccg-cct#122]
Duplicate data in SearchSimilarSearchJob table. See attachment for more details. 

![image](https://user-images.githubusercontent.com/82117975/124645466-75886880-de61-11eb-9868-6cb411abba43.png)

**Comment by trudge-64** [comment]
The reason why it shows duplicated data is because any position that appears at 100% also needs to be included for the 90%, 80% and 70%

**Comment by ccg-lem** [comment]
@raminderus @alfredboum only requires change to reseed data, no change to table structure

**Comment by alfredboum** [comment]
Issue fixed

**Comment by trudge-64** [comment]
> Issue fixed

Alfred, I don't see any changes in the Similar Search table and no push for the fix. Are you sure your comment is in for this issue?

**Comment by alfredboum** [comment]
Hi Theresa,
I created a pull request, you can see the changes.
Thanks

________________________________
De : trudge-64 ***@***.***>
Envoyé : 14 juillet 2021 10:33
À : dfo-mpo/ccg-cct ***@***.***>
Cc : alfredboum ***@***.***>; Mention ***@***.***>
Objet : Re: [dfo-mpo/ccg-cct] Fix SearchSimilarJob table in Database (#122)


Issue fixed

Alfred, I don't see any changes in the Similar Search table and no push for the fix. Are you sure your comment is in for this issue?

**Comment by ccg-lem** [comment]
@alfredboum There is still duplicate data in the hundred/ninety/eighty/seventy percent categories. Please review the PR

**Comment by alfredboum** [comment]
ok got it

________________________________
De : ccg-lem ***@***.***>
Envoyé : 14 juillet 2021 12:11
À : dfo-mpo/ccg-cct ***@***.***>
Cc : alfredboum ***@***.***>; Mention ***@***.***>
Objet : Re: [dfo-mpo/ccg-cct] Fix SearchSimilarJob table in Database (#122)


@alfredboum<https://github.com/alfredboum> There is still duplicate data in the hundred/ninety/eighty/seventy percent categories. Please review the PR
