### ISSUE TITLE
PositionId Values in Similar Search table need to all begin with &

### ISSUE THREAD

**Issue by drudn** [dfo-mpo/ccg-cct#126]
This is because the forms for editing similar position perform a split on "&PositionId=" to extract the id values, as the actual string is too long to pass as a query parameter.

**Comment by trudge-64** [comment]
This is how I entered them into the table, 
HundredPercent = "PositionId=362&PositionId=363&PositionId=364", NinetyPercent = "PositionId=362&PositionId=363&PositionId=364&PositionId=365&PositionId=214&PositionId=215", etc...

**Comment by drudn** [comment]
Needs to be HundredPercent = "&PositionId=362&PositionId=363&PositionId=364", NinetyPercent = "&PositionId=362&PositionId=363&PositionId=364&PositionId=365&PositionId=214&PositionId=215", etc...

Only the character '&' needs to be added to all records at the beginning.

**Comment by trudge-64** [comment]
Oh I see I forgot to add the & at the beginning of each one.
-------- Original message --------From: Dan Rudnicki ***@***.***> Date: 2021-07-09  3:03 p.m.  (GMT-05:00) To: dfo-mpo/ccg-cct ***@***.***> Cc: trudge-64 ***@***.***>, Comment ***@***.***> Subject: Re: [dfo-mpo/ccg-cct] PositionId Values in Similar Search table need to all begin with & (#126) 
Needs to be HundredPercent = "&PositionId=362&PositionId=363&PositionId=364", NinetyPercent = "&PositionId=362&PositionId=363&PositionId=364&PositionId=365&PositionId=214&PositionId=215", etc...
Only the character '&' needs to be added to all records at the beginning.

**Comment by ccg-lem** [comment]
@alfred84-boum @raminderus Since this is for the same table, can we include this fix with #122 ?
