### ISSUE TITLE
Add Seagoing/Shoreside option for Student pathway in CCT Web

### ISSUE THREAD

**Issue by ccg-lem** [dfo-mpo/ccg-cct#96]
To avoid duplication of data in student job categories, add a Shoreside/Seagoing option selection for Student path way. (Same as External Members)

![image](https://user-images.githubusercontent.com/82117975/123309088-7977ca80-d4f2-11eb-8526-d75d0007b9b7.png)

**Comment by trudge-64** [comment]
Updated Student section and Resource files. Also updated PDF viewer and created pull request
